/* Generated by AN DISI Unibo */ 
package it.unibo.ctxReqConsole;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxReqConsole  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxreqconsole", "./srcMore/it/unibo/ctxReqConsole/finalsys2018req.pl", 
		"./srcMore/it/unibo/ctxReqConsole/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
