/* Generated by AN DISI Unibo */ 
package it.unibo.reqlamp;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Reqlamp extends QActorMsgQueue{
	public MsgHandle_Reqlamp(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
