/* Generated by AN DISI Unibo */ 
package it.unibo.reqclock;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Reqclock extends QActorMsgQueue{
	public MsgHandle_Reqclock(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
