/* Generated by AN DISI Unibo */ 
package it.unibo.blinker;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractBlinker extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractBlinker(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/blinker/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/blinker/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("listen",listen);
	    	stateTab.put("checkStart",checkStart);
	    	stateTab.put("blinkOn",blinkOn);
	    	stateTab.put("blinkOff",blinkOff);
	    	stateTab.put("checkEnd",checkEnd);
	    	stateTab.put("blinkStop",blinkStop);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "blinker tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"Blinker ready...\"";
	    	println( temporaryStr );  
	     connectToMqttServer("tcp://localhost:1883");
	    	//switchTo listen
	        switchToPlanAsNextState(pr, myselfName, "blinker_"+myselfName, 
	              "listen",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun listen = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_listen",0);
	     pr.incNumIter(); 	
	    	String myselfName = "listen";  
	    	//bbb
	     msgTransition( pr,myselfName,"blinker_"+myselfName,false,
	          new StateFun[]{stateTab.get("checkStart") }, 
	          new String[]{"true","M","ctrlMsg" },
	          36000000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_listen){  
	    	 println( getName() + " plan=listen WARNING:" + e_listen.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//listen
	    
	    StateFun checkStart = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("checkStart",-1);
	    	String myselfName = "checkStart";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("ctrlMsg(blinker,on)");
	    	if( currentMessage != null && currentMessage.msgId().equals("ctrlMsg") && 
	    		pengine.unify(curT, Term.createTerm("ctrlMsg(TARGET,PAYLOAD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="shouldBlink";
	    		/* AddRule */
	    		parg = updateVars(Term.createTerm("ctrlMsg(TARGET,PAYLOAD)"),  Term.createTerm("ctrlMsg(blinker,on)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) addRule(parg);	    		  					
	    	}
	    	//switchTo blinkOn
	        switchToPlanAsNextState(pr, myselfName, "blinker_"+myselfName, 
	              "blinkOn",false, true, " ??shouldBlink"); 
	    }catch(Exception e_checkStart){  
	    	 println( getName() + " plan=checkStart WARNING:" + e_checkStart.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//checkStart
	    
	    StateFun blinkOn = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_blinkOn",0);
	     pr.incNumIter(); 	
	    	String myselfName = "blinkOn";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(TARGET,PAYLOAD)","ctrlEvent(hueLamp,on)", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//bbb
	     msgTransition( pr,myselfName,"blinker_"+myselfName,false,
	          new StateFun[]{stateTab.get("checkEnd") }, 
	          new String[]{"true","M","ctrlMsg" },
	          1000, "blinkOff" );//msgTransition
	    }catch(Exception e_blinkOn){  
	    	 println( getName() + " plan=blinkOn WARNING:" + e_blinkOn.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//blinkOn
	    
	    StateFun blinkOff = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_blinkOff",0);
	     pr.incNumIter(); 	
	    	String myselfName = "blinkOff";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(TARGET,PAYLOAD)","ctrlEvent(hueLamp,off)", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//bbb
	     msgTransition( pr,myselfName,"blinker_"+myselfName,false,
	          new StateFun[]{stateTab.get("checkEnd") }, 
	          new String[]{"true","M","ctrlMsg" },
	          1000, "blinkOn" );//msgTransition
	    }catch(Exception e_blinkOff){  
	    	 println( getName() + " plan=blinkOff WARNING:" + e_blinkOff.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//blinkOff
	    
	    StateFun checkEnd = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("checkEnd",-1);
	    	String myselfName = "checkEnd";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("ctrlMsg(blinker,off)");
	    	if( currentMessage != null && currentMessage.msgId().equals("ctrlMsg") && 
	    		pengine.unify(curT, Term.createTerm("ctrlMsg(TARGET,PAYLOAD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="shouldStop";
	    		/* AddRule */
	    		parg = updateVars(Term.createTerm("ctrlMsg(TARGET,PAYLOAD)"),  Term.createTerm("ctrlMsg(blinker,off)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) addRule(parg);	    		  					
	    	}
	    	//switchTo blinkStop
	        switchToPlanAsNextState(pr, myselfName, "blinker_"+myselfName, 
	              "blinkStop",false, true, " ??shouldStop"); 
	    }catch(Exception e_checkEnd){  
	    	 println( getName() + " plan=checkEnd WARNING:" + e_checkEnd.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//checkEnd
	    
	    StateFun blinkStop = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("blinkStop",-1);
	    	String myselfName = "blinkStop";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(TARGET,PAYLOAD)","ctrlEvent(hueLamp,off)", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//switchTo listen
	        switchToPlanAsNextState(pr, myselfName, "blinker_"+myselfName, 
	              "listen",false, false, null); 
	    }catch(Exception e_blinkStop){  
	    	 println( getName() + " plan=blinkStop WARNING:" + e_blinkStop.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//blinkStop
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
