/* Generated by AN DISI Unibo */ 
package it.unibo.blinker;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Blinker extends QActorMsgQueue{
	public MsgHandle_Blinker(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
