/* Generated by AN DISI Unibo */ 
package it.unibo.reqtherm;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Reqtherm extends QActorMsgQueue{
	public MsgHandle_Reqtherm(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
