/* Generated by AN DISI Unibo */ 
package it.unibo.ctxReqRobot;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxReqRobot  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxreqrobot", "./srcMore/it/unibo/ctxReqRobot/finalsys2018req.pl", 
		"./srcMore/it/unibo/ctxReqRobot/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
