/* Generated by AN DISI Unibo */ 
package it.unibo.ctxFinalSysTesting;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxFinalSysTesting  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxfinalsystesting", "./srcMore/it/unibo/ctxFinalSysTesting/finalsys2018testing.pl", 
		"./srcMore/it/unibo/ctxFinalSysTesting/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
