/* Generated by AN DISI Unibo */ 
package it.unibo.reqrobot;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Reqrobot extends QActorMsgQueue{
	public MsgHandle_Reqrobot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
