/* Generated by AN DISI Unibo */ 
package it.unibo.lampadapter;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Lampadapter extends QActorMsgQueue{
	public MsgHandle_Lampadapter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
