/* Generated by AN DISI Unibo */ 
package it.unibo.ctxReqSensorsActuators;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxReqSensorsActuators  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxreqsensorsactuators", "./srcMore/it/unibo/ctxReqSensorsActuators/finalsys2018req.pl", 
		"./srcMore/it/unibo/ctxReqSensorsActuators/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
