/* Generated by AN DISI Unibo */ 
package it.unibo.cleaner;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Cleaner extends QActorMsgQueue{
	public MsgHandle_Cleaner(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
